// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzfxupwyysarzyegpuss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6Znh1cHd5eXNhcnp5ZWdwdXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMTgyNjAsImV4cCI6MjA3NzY5NDI2MH0._-uIpvuxnJA0mhXEfmJvlrUl_5qtwsti0kMVGE5sOuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
